/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLog {
  'id' : string,
  'action' : string,
  'user_id' : string,
  'timestamp' : bigint,
  'details' : string,
}
export interface Assignment {
  'id' : string,
  'operator_id' : string,
  'action' : string,
  'timestamp' : bigint,
  'location' : string,
  'equipment_id' : string,
}
export interface Equipment {
  'id' : string,
  'status' : string,
  'last_update_time' : bigint,
  'name' : string,
  'last_location' : string,
  'assigned_operator' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface Issue {
  'id' : string,
  'status' : string,
  'operator_id' : string,
  'grounded' : boolean,
  'notes' : string,
  'timestamp' : bigint,
  'category' : string,
  'photo' : [] | [ExternalBlob],
  'location' : string,
  'equipment_id' : string,
}
export interface Session {
  'id' : string,
  'role' : string,
  'display_name' : string,
  'login_time' : bigint,
  'employee_id' : string,
}
export interface UserProfile {
  'role' : string,
  'display_name' : string,
  'login_time' : bigint,
  'employee_id' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addEquipment' : ActorMethod<[Equipment], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAssignment' : ActorMethod<[Assignment], undefined>,
  'createSession' : ActorMethod<[Session], undefined>,
  'getActivityLogsByUser' : ActorMethod<[string], Array<ActivityLog>>,
  'getAllActivityLogs' : ActorMethod<[], Array<ActivityLog>>,
  'getAllAssignments' : ActorMethod<[], Array<Assignment>>,
  'getAllEquipment' : ActorMethod<[], Array<Equipment>>,
  'getAllIssues' : ActorMethod<[], Array<Issue>>,
  'getAllSessions' : ActorMethod<[], Array<Session>>,
  'getAssignmentsByOperator' : ActorMethod<[string], Array<Assignment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentTime' : ActorMethod<[], bigint>,
  'getDemoOperatorCredentials' : ActorMethod<
    [],
    {
      'password' : string,
      'role' : string,
      'email' : string,
      'display_name' : string,
      'employee_id' : string,
    }
  >,
  'getEquipment' : ActorMethod<[string], [] | [Equipment]>,
  'getOpenIssues' : ActorMethod<[], Array<Issue>>,
  'getSession' : ActorMethod<[string], [] | [Session]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logActivity' : ActorMethod<[ActivityLog], undefined>,
  'reportIssue' : ActorMethod<[Issue], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEquipment' : ActorMethod<[Equipment], undefined>,
  'updateIssue' : ActorMethod<[Issue], undefined>,
  'validateEmployeeId' : ActorMethod<
    [string],
    { 'role' : string, 'isValid' : boolean }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];