/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Equipment = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'last_update_time' : IDL.Int,
  'name' : IDL.Text,
  'last_location' : IDL.Text,
  'assigned_operator' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Assignment = IDL.Record({
  'id' : IDL.Text,
  'operator_id' : IDL.Text,
  'action' : IDL.Text,
  'timestamp' : IDL.Int,
  'location' : IDL.Text,
  'equipment_id' : IDL.Text,
});
export const Session = IDL.Record({
  'id' : IDL.Text,
  'role' : IDL.Text,
  'display_name' : IDL.Text,
  'login_time' : IDL.Int,
  'employee_id' : IDL.Text,
});
export const ActivityLog = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'user_id' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Issue = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'operator_id' : IDL.Text,
  'grounded' : IDL.Bool,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'location' : IDL.Text,
  'equipment_id' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'role' : IDL.Text,
  'display_name' : IDL.Text,
  'login_time' : IDL.Int,
  'employee_id' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addEquipment' : IDL.Func([Equipment], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAssignment' : IDL.Func([Assignment], [], []),
  'createSession' : IDL.Func([Session], [], []),
  'getActivityLogsByUser' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ActivityLog)],
      ['query'],
    ),
  'getAllActivityLogs' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
  'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'getAllEquipment' : IDL.Func([], [IDL.Vec(Equipment)], ['query']),
  'getAllIssues' : IDL.Func([], [IDL.Vec(Issue)], ['query']),
  'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getAssignmentsByOperator' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentTime' : IDL.Func([], [IDL.Int], ['query']),
  'getDemoOperatorCredentials' : IDL.Func(
      [],
      [
        IDL.Record({
          'password' : IDL.Text,
          'role' : IDL.Text,
          'email' : IDL.Text,
          'display_name' : IDL.Text,
          'employee_id' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getEquipment' : IDL.Func([IDL.Text], [IDL.Opt(Equipment)], ['query']),
  'getOpenIssues' : IDL.Func([], [IDL.Vec(Issue)], ['query']),
  'getSession' : IDL.Func([IDL.Text], [IDL.Opt(Session)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logActivity' : IDL.Func([ActivityLog], [], []),
  'reportIssue' : IDL.Func([Issue], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEquipment' : IDL.Func([Equipment], [], []),
  'updateIssue' : IDL.Func([Issue], [], []),
  'validateEmployeeId' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'role' : IDL.Text, 'isValid' : IDL.Bool })],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Equipment = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'last_update_time' : IDL.Int,
    'name' : IDL.Text,
    'last_location' : IDL.Text,
    'assigned_operator' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Assignment = IDL.Record({
    'id' : IDL.Text,
    'operator_id' : IDL.Text,
    'action' : IDL.Text,
    'timestamp' : IDL.Int,
    'location' : IDL.Text,
    'equipment_id' : IDL.Text,
  });
  const Session = IDL.Record({
    'id' : IDL.Text,
    'role' : IDL.Text,
    'display_name' : IDL.Text,
    'login_time' : IDL.Int,
    'employee_id' : IDL.Text,
  });
  const ActivityLog = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'user_id' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Issue = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'operator_id' : IDL.Text,
    'grounded' : IDL.Bool,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'location' : IDL.Text,
    'equipment_id' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'role' : IDL.Text,
    'display_name' : IDL.Text,
    'login_time' : IDL.Int,
    'employee_id' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addEquipment' : IDL.Func([Equipment], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAssignment' : IDL.Func([Assignment], [], []),
    'createSession' : IDL.Func([Session], [], []),
    'getActivityLogsByUser' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ActivityLog)],
        ['query'],
      ),
    'getAllActivityLogs' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
    'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'getAllEquipment' : IDL.Func([], [IDL.Vec(Equipment)], ['query']),
    'getAllIssues' : IDL.Func([], [IDL.Vec(Issue)], ['query']),
    'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getAssignmentsByOperator' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentTime' : IDL.Func([], [IDL.Int], ['query']),
    'getDemoOperatorCredentials' : IDL.Func(
        [],
        [
          IDL.Record({
            'password' : IDL.Text,
            'role' : IDL.Text,
            'email' : IDL.Text,
            'display_name' : IDL.Text,
            'employee_id' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getEquipment' : IDL.Func([IDL.Text], [IDL.Opt(Equipment)], ['query']),
    'getOpenIssues' : IDL.Func([], [IDL.Vec(Issue)], ['query']),
    'getSession' : IDL.Func([IDL.Text], [IDL.Opt(Session)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logActivity' : IDL.Func([ActivityLog], [], []),
    'reportIssue' : IDL.Func([Issue], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEquipment' : IDL.Func([Equipment], [], []),
    'updateIssue' : IDL.Func([Issue], [], []),
    'validateEmployeeId' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'role' : IDL.Text, 'isValid' : IDL.Bool })],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };