/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Session {
    id: string;
    role: string;
    display_name: string;
    login_time: bigint;
    employee_id: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Issue {
    id: string;
    status: string;
    operator_id: string;
    grounded: boolean;
    notes: string;
    timestamp: bigint;
    category: string;
    photo?: ExternalBlob;
    location: string;
    equipment_id: string;
}
export interface Equipment {
    id: string;
    status: string;
    last_update_time: bigint;
    name: string;
    last_location: string;
    assigned_operator?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Assignment {
    id: string;
    operator_id: string;
    action: string;
    timestamp: bigint;
    location: string;
    equipment_id: string;
}
export interface ActivityLog {
    id: string;
    action: string;
    user_id: string;
    timestamp: bigint;
    details: string;
}
export interface UserProfile {
    role: string;
    display_name: string;
    login_time: bigint;
    employee_id: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addEquipment(equipmentData: Equipment): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAssignment(assignmentData: Assignment): Promise<void>;
    createSession(sessionData: Session): Promise<void>;
    getActivityLogsByUser(userId: string): Promise<Array<ActivityLog>>;
    getAllActivityLogs(): Promise<Array<ActivityLog>>;
    getAllAssignments(): Promise<Array<Assignment>>;
    getAllEquipment(): Promise<Array<Equipment>>;
    getAllIssues(): Promise<Array<Issue>>;
    getAllSessions(): Promise<Array<Session>>;
    getAssignmentsByOperator(operatorId: string): Promise<Array<Assignment>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentTime(): Promise<bigint>;
    getDemoOperatorCredentials(): Promise<{
        password: string;
        role: string;
        email: string;
        display_name: string;
        employee_id: string;
    }>;
    getEquipment(id: string): Promise<Equipment | null>;
    getOpenIssues(): Promise<Array<Issue>>;
    getSession(id: string): Promise<Session | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    logActivity(activityData: ActivityLog): Promise<void>;
    reportIssue(issueData: Issue): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateEquipment(equipmentData: Equipment): Promise<void>;
    updateIssue(issueData: Issue): Promise<void>;
    validateEmployeeId(employeeId: string): Promise<{
        role: string;
        isValid: boolean;
    }>;
}
import type { Equipment as _Equipment, ExternalBlob as _ExternalBlob, Issue as _Issue, Session as _Session, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addEquipment(arg0: Equipment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEquipment(to_candid_Equipment_n8(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEquipment(to_candid_Equipment_n8(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createAssignment(arg0: Assignment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssignment(arg0);
            return result;
        }
    }
    async createSession(arg0: Session): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0);
            return result;
        }
    }
    async getActivityLogsByUser(arg0: string): Promise<Array<ActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLogsByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLogsByUser(arg0);
            return result;
        }
    }
    async getAllActivityLogs(): Promise<Array<ActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActivityLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActivityLogs();
            return result;
        }
    }
    async getAllAssignments(): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssignments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssignments();
            return result;
        }
    }
    async getAllEquipment(): Promise<Array<Equipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEquipment();
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEquipment();
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllIssues(): Promise<Array<Issue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIssues();
                return from_candid_vec_n16(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIssues();
            return from_candid_vec_n16(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllSessions(): Promise<Array<Session>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSessions();
            return result;
        }
    }
    async getAssignmentsByOperator(arg0: string): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignmentsByOperator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignmentsByOperator(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCurrentTime(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentTime();
            return result;
        }
    }
    async getDemoOperatorCredentials(): Promise<{
        password: string;
        role: string;
        email: string;
        display_name: string;
        employee_id: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDemoOperatorCredentials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDemoOperatorCredentials();
            return result;
        }
    }
    async getEquipment(arg0: string): Promise<Equipment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEquipment(arg0);
                return from_candid_opt_n24(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEquipment(arg0);
            return from_candid_opt_n24(this.uploadFile, this.downloadFile, result);
        }
    }
    async getOpenIssues(): Promise<Array<Issue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenIssues();
                return from_candid_vec_n16(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenIssues();
            return from_candid_vec_n16(this.uploadFile, this.downloadFile, result);
        }
    }
    async getSession(arg0: string): Promise<Session | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logActivity(arg0: ActivityLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logActivity(arg0);
            return result;
        }
    }
    async reportIssue(arg0: Issue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportIssue(await to_candid_Issue_n26(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportIssue(await to_candid_Issue_n26(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateEquipment(arg0: Equipment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEquipment(to_candid_Equipment_n8(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEquipment(to_candid_Equipment_n8(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateIssue(arg0: Issue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIssue(await to_candid_Issue_n26(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIssue(await to_candid_Issue_n26(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async validateEmployeeId(arg0: string): Promise<{
        role: string;
        isValid: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.validateEmployeeId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateEmployeeId(arg0);
            return result;
        }
    }
}
function from_candid_Equipment_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Equipment): Equipment {
    return from_candid_record_n14(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
async function from_candid_Issue_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Issue): Promise<Issue> {
    return await from_candid_record_n18(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n20(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Equipment]): Equipment | null {
    return value.length === 0 ? null : from_candid_Equipment_n13(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Session]): Session | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    last_update_time: bigint;
    name: string;
    last_location: string;
    assigned_operator: [] | [string];
}): {
    id: string;
    status: string;
    last_update_time: bigint;
    name: string;
    last_location: string;
    assigned_operator?: string;
} {
    return {
        id: value.id,
        status: value.status,
        last_update_time: value.last_update_time,
        name: value.name,
        last_location: value.last_location,
        assigned_operator: record_opt_to_undefined(from_candid_opt_n15(uploadFile, downloadFile, value.assigned_operator))
    };
}
async function from_candid_record_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    operator_id: string;
    grounded: boolean;
    notes: string;
    timestamp: bigint;
    category: string;
    photo: [] | [_ExternalBlob];
    location: string;
    equipment_id: string;
}): Promise<{
    id: string;
    status: string;
    operator_id: string;
    grounded: boolean;
    notes: string;
    timestamp: bigint;
    category: string;
    photo?: ExternalBlob;
    location: string;
    equipment_id: string;
}> {
    return {
        id: value.id,
        status: value.status,
        operator_id: value.operator_id,
        grounded: value.grounded,
        notes: value.notes,
        timestamp: value.timestamp,
        category: value.category,
        photo: record_opt_to_undefined(await from_candid_opt_n19(uploadFile, downloadFile, value.photo)),
        location: value.location,
        equipment_id: value.equipment_id
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Equipment>): Array<Equipment> {
    return value.map((x)=>from_candid_Equipment_n13(uploadFile, downloadFile, x));
}
async function from_candid_vec_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Issue>): Promise<Array<Issue>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Issue_n17(uploadFile, downloadFile, x)));
}
function to_candid_Equipment_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Equipment): _Equipment {
    return to_candid_record_n9(uploadFile, downloadFile, value);
}
async function to_candid_ExternalBlob_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
async function to_candid_Issue_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Issue): Promise<_Issue> {
    return await to_candid_record_n27(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
async function to_candid_record_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    operator_id: string;
    grounded: boolean;
    notes: string;
    timestamp: bigint;
    category: string;
    photo?: ExternalBlob;
    location: string;
    equipment_id: string;
}): Promise<{
    id: string;
    status: string;
    operator_id: string;
    grounded: boolean;
    notes: string;
    timestamp: bigint;
    category: string;
    photo: [] | [_ExternalBlob];
    location: string;
    equipment_id: string;
}> {
    return {
        id: value.id,
        status: value.status,
        operator_id: value.operator_id,
        grounded: value.grounded,
        notes: value.notes,
        timestamp: value.timestamp,
        category: value.category,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n28(uploadFile, downloadFile, value.photo)) : candid_none(),
        location: value.location,
        equipment_id: value.equipment_id
    };
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    last_update_time: bigint;
    name: string;
    last_location: string;
    assigned_operator?: string;
}): {
    id: string;
    status: string;
    last_update_time: bigint;
    name: string;
    last_location: string;
    assigned_operator: [] | [string];
} {
    return {
        id: value.id,
        status: value.status,
        last_update_time: value.last_update_time,
        name: value.name,
        last_location: value.last_location,
        assigned_operator: value.assigned_operator ? candid_some(value.assigned_operator) : candid_none()
    };
}
function to_candid_variant_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
